services:
  post-db-manager:
    build:
      context: social-media-db-manager
    ports:
      - 8000:8000
    env_file:
      - social-media-db-manager/local.env

  public-api:
    build:
      context: public-api
    ports:
      - 8001:8001
    env_file:
      - public-api/local.env

  curator:
    build: 
      context: curator
    ports:
      - 8002:8002
    env_file:
      - curator/local.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512mb


  db:
    build: 
      context: postgres-db
      dockerfile: Dockerfile
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - ./postgres-db/test_dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
     - 5432:5432